# Generated by Django 4.2.5 on 2023-10-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor_data",
            name="light_intensity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sensor_data",
            name="soil_moisture",
            field=models.IntegerField(null=True),
        ),
    ]
