# Generated by Django 4.2.5 on 2023-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0002_sensor_data_light_intensity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor_data",
            name="humidity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sensor_data",
            name="temp",
            field=models.IntegerField(null=True),
        ),
    ]
